---
# tasks file for shinken

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: shinken

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags: shinken

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: shinken

- include: FreeBSD.yml
  when: ansible_distribution == "FreeBSD"
  tags: shinken

- name: Create Shinken user
  user: >
    name=shinken
    createhome=yes
    state=present
  tags: shinken

- name: Install Shinken
  pip: >
    name=shinken
    version={{ shinken_version }}
    state=present
  tags: shinken

- name: Install Shinken WebUI2 dependencies
  pip: >
    name={{ item.key }}
    version={{ item.value.version }}
    state=present
  with_dict: shinken_module_webui2_dependencies
  when: "'webui2' in shinken_modules"
  tags: shinken

- name: Initialize Shinken
  become: yes
  become_user: shinken
  become_method: sudo
  command: shinken --init
  args:
    creates: /home/shinken/.shinken.ini
  tags: shinken

- name: Install Shinken modules
  become: yes
  become_user: shinken
  become_method: sudo
  command: shinken install {{ item }}
  args:
    creates: /var/lib/shinken/modules/{{ item }}
  with_items: shinken_modules
  tags: shinken

- name: Create Shiken main configuration file
  template: >
    src=shinken.cfg.j2
    dest=/etc/shinken/shinken.cfg
    owner=shinken
    group=shinken
    mode=0644
  notify: restart shinken
  tags: shinken

- name: Create Shinken broker master configuration file
  template: >
    src=brokers/broker-master.cfg.j2
    dest=/etc/shinken/brokers/broker-master.cfg
    owner=shinken
    group=shinken
    mode=0644
  notify: restart shinken
  tags: shinken

- name: Create Shinken WebUI2 module configuration file
  template: >
    src=modules/webui2.cfg.j2
    dest=/etc/shinken/modules/webui2.cfg
    owner=shinken
    group=shinken
    mode=0640
  when: "'webui2' in shinken_modules"
  notify: restart shinken
  tags: shinken

- name: Ensure Shinken service is started and enabled on boot
  service: name={{ shinken_service_name }} state=started enabled=yes
  tags: shinken
